<a href="https://colab.research.google.com/github/RedBatProject/ufo-works/blob/main/test_dadmatech.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Not wrking

In [1]:
%cd Nevise

/content/Nevise


In [2]:
!pip install -r requirements.txt

  Using cached clean_text-0.3.0-py3-none-any.whl (9.6 kB)
  Using cached hazm-0.7.0-py3-none-any.whl (316 kB)
  Using cached numpy-1.19.5.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached tqdm-4.46.1-py2.py3-none-any.whl (63 kB)
  Using cached transformers-4.3.3-py3-none-any.whl (1.9 MB)
  Using cached emoji-2.12.1-py3-none-any.whl (431 kB)
  Using cached ftfy-5.9-py3-none-any.whl
  Using cached nltk-3.3-py3-none-any.whl
  Using cached libwapiti-0.2.1-cp310-cp310-linux_x86_64.whl
  Using cached sacremoses-0.1.1-py3-none-any.whl (897 kB)
  Using cached tokenizers-0.10.3.tar.gz (212 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  error: subprocess-exited-with-error
  
  × Building wheel for numpy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  

In [2]:
!git clone https://github.com/Dadmatech/Nevise.git

Cloning into 'Nevise'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 39 (delta 19), reused 12 (delta 2), pack-reused 0
Receiving objects: 100% (39/39), 14.90 KiB | 7.45 MiB/s, done.
Resolving deltas: 100% (19/19), done.


In [4]:
ls

helpers.py  main.py  model/  models.py  __pycache__/  README.md  requirements.txt  utils.py


In [5]:
%cd model

/content/Nevise/model


In [13]:
!gdown https://drive.google.com/uc?id=1Ki5WGR4yxftDEjROQLf9Br8KHef95k1F

Downloading...
From (original): https://drive.google.com/uc?id=1Ki5WGR4yxftDEjROQLf9Br8KHef95k1F
From (redirected): https://drive.google.com/uc?id=1Ki5WGR4yxftDEjROQLf9Br8KHef95k1F&confirm=t&uuid=0ec50354-5645-46e3-ae78-0122d5d95571
To: /content/Nevise/model/model.pth.tar
100% 2.87G/2.87G [00:51<00:00, 56.3MB/s]


In [8]:
!gdown https://drive.google.com/uc?id=1nKeMdDnxIJpOv-OeFj00UnhoChuaY5Ns


Downloading...
From: https://drive.google.com/uc?id=1nKeMdDnxIJpOv-OeFj00UnhoChuaY5Ns
To: /content/Nevise/model/vocab.pkl
100% 3.80M/3.80M [00:00<00:00, 216MB/s]


In [14]:
%cd ..

/content/Nevise


In [15]:
ls

helpers.py  main.py  model/  models.py  README.md  requirements.txt  utils.py


In [7]:
!python main.py

loading vocab from model/vocab.pkl
pytorch_model.bin: 100% 654M/654M [00:05<00:00, 125MB/s]
SubwordBert(
  (bert_dropout): Dropout(p=0.2, inplace=False)
  (bert_model): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(100000, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput

In [10]:
def custom_bert_tokenize_sentence(list_of_texts):
    out = [custom_bert_tokenize_sentence(text) for text in list_of_texts]
    texts, tokens, split_sizes = list(zip(*out))
    return [*texts], [*tokens], [*split_sizes]

In [19]:
custom_bert_tokenize_sentence(['سلام','سلام'])

RecursionError: maximum recursion depth exceeded

In [15]:
def c(x):
    if x ==1:
        return x
    else:
        x = x-1
        return c(x)

In [17]:
c(20)

1

In [20]:
import pickle

In [21]:
with open('/content/Nevise/model/vocab.pkl', 'rb') as fp:
    vocab = pickle.load(fp)

In [22]:
vocab

{'token2idx': {'.': 0,
  'در': 1,
  'و': 2,
  'به': 3,
  '،': 4,
  'از': 5,
  'این': 6,
  'که': 7,
  'را': 8,
  'است': 9,
  'با': 10,
  ':': 11,
  'برای': 12,
  'یک': 13,
  ')': 14,
  '(': 15,
  'کرد': 16,
  'آن': 17,
  'سال': 18,
  'هم': 19,
  '«': 20,
  '»': 21,
  'شد': 22,
  'تا': 23,
  'خود': 24,
  'وی': 25,
  'دارد': 26,
  'بود': 27,
  'ایران': 28,
  'او': 29,
  'بر': 30,
  'ما': 31,
  'می\u200cشود': 32,
  'نیز': 33,
  'کشور': 34,
  'باید': 35,
  'گفت': 36,
  '؟': 37,
  'اما': 38,
  'تغییرمسیر': 39,
  'قرار': 40,
  'دو': 41,
  'یا': 42,
  'مردم': 43,
  'شده': 44,
  'دیگر': 45,
  'کار': 46,
  'داد': 47,
  'من': 48,
  'می\u200cکند': 49,
  'هر': 50,
  'تیم': 51,
  'استان': 52,
  'دولت': 53,
  'کند': 54,
  'هستند': 55,
  'شهر': 56,
  'شود': 57,
  'روز': 58,
  'یکی': 59,
  'آمریکا': 60,
  'انتخابات': 61,
  'ادامه': 62,
  'شده_است': 63,
  'همچنین': 64,
  'عنوان': 65,
  '؛': 66,
  'اگر': 67,
  'پس': 68,
  'نفر': 69,
  'آنها': 70,
  'انجام': 71,
  'پیش': 72,
  'وجود': 73,
  'بازی': 74,
  

# New ways

In [4]:
import re

def get_sentences_splitters(txt):
    splitters =  ['? ', '! ', '. ', '.\n', '?\n', '!\n', ' ؟', '\n؟']
    all_sents = []
    last_sent_index= 0
    for i, (ch1, ch2) in enumerate(zip(txt, txt[1:])):
        if ch1 + ch2 in splitters:
            all_sents.append((txt[last_sent_index:i+len(ch1)],ch2))
            last_sent_index = i+ len(ch1+ch2)
    all_sents.append((txt[last_sent_index:], None))
    return [item[0] for item in all_sents], [item[1] for item in all_sents[:-1]]

def space_special_chars(txt):
    return re.sub('([.:،<>,!?()])', r' \1 ', txt)

def de_space_special_chars(txt):
    txt = re.sub('( ([.:،<>,!?()]) )', r'\2', txt)
    txt = re.sub('( ([.:،<>,!?()]))', r'\2', txt)
    return re.sub('(([.:،<>,!?()]) )', r'\2', txt)

In [1]:
!pip install hazm==0.7.0

In [2]:
# !pip show hazm

Name: hazm
Version: 0.7.0
Summary: Python library for digesting Persian text.
Home-page: http://www.sobhe.ir/hazm/
Author: Alireza Nourian
Author-email: az.nourian@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python3.10/dist-packages
Requires: libwapiti, nltk
Required-by: 


In [2]:
import os

In [3]:
%cd Nevise

/content/Nevise


In [34]:
pip show transformers

Name: transformers
Version: 4.41.1
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /usr/local/lib/python3.10/dist-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: 


In [33]:
!pip install transformers==4.3.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 7.0 MB/s eta 0:00:00
  Using cached sacremoses-0.1.1-py3-none-any.whl (897 kB)
  Using cached tokenizers-0.10.3.tar.gz (212 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  error: subprocess-exited-with-error
  
  × Building wheel for tokenizers (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tokenizers
Failed to build tokenizers
ERROR: Could not build wheels for tokenizers, which is required to install pyproject.toml-based projects


In [5]:
from hazm import Normalizer

In [6]:
import torch

In [223]:
import torch
from torch import nn
from torch.nn.utils.rnn import pad_sequence
import torch.nn.functional as F
import transformers

#################################################
# SubwordBert
#################################################


class SubwordBert(nn.Module):
    def __init__(self, screp_dim, padding_idx, output_dim):
        super(SubwordBert,self).__init__()

        self.bert_dropout = torch.nn.Dropout(0.2)
        self.bert_model = transformers.BertModel.from_pretrained("HooshvareLab/bert-fa-base-uncased")
        self.bertmodule_outdim = self.bert_model.config.hidden_size
        # Uncomment to freeze BERT layers
        # for param in self.bert_model.parameters():
        #     param.requires_grad = False

        # output module
        assert output_dim>0
        # self.dropout = nn.Dropout(p=0.4)
        self.dense = nn.Linear(self.bertmodule_outdim,output_dim)

        # loss
        # See https://pytorch.org/docs/stable/nn.html#crossentropyloss
        self.criterion = nn.CrossEntropyLoss(reduction='mean',ignore_index=padding_idx)

    @property
    def device(self) -> torch.device:
        return next(self.parameters()).device

    def get_merged_encodings(self, bert_seq_encodings, seq_splits, mode='avg'):
        bert_seq_encodings = bert_seq_encodings[:sum(seq_splits)+2,:] # 2 for [CLS] and [SEP]
        bert_seq_encodings = bert_seq_encodings[1:-1,:]
        # a tuple of tensors
        split_encoding = torch.split(bert_seq_encodings,seq_splits,dim=0)
        batched_encodings = pad_sequence(split_encoding,batch_first=True,padding_value=0)
        if mode=='avg':
            seq_splits = torch.tensor(seq_splits).reshape(-1,1).to(self.device)
            out = torch.div( torch.sum(batched_encodings,dim=1), seq_splits)
        elif mode=="add":
            out = torch.sum(batched_encodings,dim=1)
        else:
            raise Exception("Not Implemented")
        return out

    def forward(self,
                batch_bert_dict: "{'input_ids':tensor, 'attention_mask':tensor, 'token_type_ids':tensor}",
                batch_splits: "list[list[int]]",
                aux_word_embs: "tensor" = None,
                targets: "tensor" = None,
                topk = 1):

        # cnn
        batch_size = len(batch_splits)

        # bert
        # BS X max_nsubwords x self.bertmodule_outdim
        bert_encodings, cls_encoding = self.bert_model(
            input_ids=batch_bert_dict["input_ids"],
            attention_mask=batch_bert_dict["attention_mask"],
            token_type_ids=batch_bert_dict["token_type_ids"],
            return_dict=False
        )
        bert_encodings = self.bert_dropout(bert_encodings)
        # BS X max_nwords x self.bertmodule_outdim
        print(10*'=')
        print(bert_encodings.shape)
        print(10*'=')

        bert_merged_encodings = pad_sequence(
            [self.get_merged_encodings(bert_seq_encodings, seq_splits, mode='avg') \
                for bert_seq_encodings, seq_splits in zip(bert_encodings,batch_splits)],
            batch_first=True,
            padding_value=0
        )
        print(10*'=')
        print(bert_merged_encodings.shape)
        print(10*'=')

        # concat aux_embs
        # if not None, the expected dim for aux_word_embs: [BS,max_nwords,*]
        intermediate_encodings = bert_merged_encodings
        if aux_word_embs is not None:
            intermediate_encodings = torch.cat((intermediate_encodings,aux_word_embs),dim=2)

        # dense
        # [BS,max_nwords,*] or [BS,max_nwords,self.bertmodule_outdim]->[BS,max_nwords,output_dim]
        # logits = self.dense(self.dropout(intermediate_encodings))
        logits = self.dense(intermediate_encodings)

        # loss
        if targets is not None:
            assert len(targets)==batch_size                # targets:[[BS,max_nwords]
            logits_permuted = logits.permute(0, 2, 1)               # logits: [BS,output_dim,max_nwords]
            loss = self.criterion(logits_permuted,targets)

        # eval preds
        if not self.training:
            probs = F.softmax(logits,dim=-1)            # [BS,max_nwords,output_dim]
            # print('99999999999999999')
            if topk>1:
                topk_values, topk_inds = \
                    torch.topk(probs, topk, dim=-1, largest=True, sorted=True)  # -> (Tensor, LongTensor) of [BS,max_nwords,topk]
            elif topk==1:
                topk_inds = torch.argmax(probs,dim=-1)   # [BS,max_nwords]

            # Note that for those positions with padded_idx,
            #   the arg_max_prob above computes a index because
            #   the bias term leads to non-uniform values in those positions
            # print()
            return loss.cpu().detach().numpy(), topk_inds.cpu().detach().numpy()
        return loss

In [224]:
def load_vocab_dict(path_: str):
    """
    path_: path where the vocab pickle file is saved
    """
    with open(path_, 'rb') as fp:
        vocab = pickle.load(fp)
    return vocab

In [225]:
def get_model_nparams(model):
    ntotal = 0
    for param in list(model.parameters()):
        temp = 1
        for sz in list(param.size()): temp*=sz
        ntotal += temp
    return ntotal

In [226]:
def load_model(vocab):
    model = SubwordBert(3*len(vocab["chartoken2idx"]),vocab["token2idx"][ vocab["pad_token"] ],len(vocab["token_freq"]))
    print(model)
    print(get_model_nparams(model) )
    return model

In [227]:
def load_pretrained(model, checkpoint_path, optimizer=None, device='cuda'):
    if torch.cuda.is_available() and device != "cpu":
        map_location = lambda storage, loc: storage.cuda()
    else:
        map_location = 'cpu'
    print(f"Loading model params from checkpoint dir: {checkpoint_path}")
    checkpoint_data = torch.load(checkpoint_path, map_location=map_location)
    # print(checkpoint_data['model_state_dict'])
    model.load_state_dict(checkpoint_data['model_state_dict'],strict=False)
    if optimizer is not None:
        optimizer.load_state_dict(checkpoint_data['optimizer_state_dict'],strict=False)
    max_dev_acc, argmax_dev_acc = checkpoint_data["max_dev_acc"], checkpoint_data["argmax_dev_acc"]

    if optimizer is not None:
        return model, optimizer, max_dev_acc, argmax_dev_acc
    return model

In [228]:
def load_pre_model(vocab_path, model_checkpoint_path):
    DEVICE = "cuda:0" if torch.cuda.is_available() else "cpu"
    print(f"loading vocab from {vocab_path}")
    vocab = load_vocab_dict(vocab_path)
    model = load_model(vocab)
    model = load_pretrained(model, model_checkpoint_path)
    return model, vocab, DEVICE

In [229]:
import time

In [230]:
from tqdm import tqdm

In [231]:
import numpy as np

In [232]:


def batch_iter(data, batch_size, shuffle):
    """
    each data item is a tuple of lables and text
    """
    n_batches = int(np.ceil(len(data) / batch_size))
    indices = list(range(len(data)))
    if shuffle:  np.random.shuffle(indices)

    for i in range(n_batches):
        batch_indices = indices[i * batch_size: (i + 1) * batch_size]
        batch_labels = [data[idx][0] for idx in batch_indices]
        batch_sentences = [data[idx][1] for idx in batch_indices]

        yield (batch_labels,batch_sentences)


In [233]:
import transformers

In [234]:
def merge_subtokens(tokens: "list"):
    merged_tokens = []
    for token in tokens:
        if token.startswith("##"): merged_tokens[-1] = merged_tokens[-1]+token[2:]
        else: merged_tokens.append(token)
        # print(merged_tokens)
    text = " ".join(merged_tokens)
    return text


In [235]:
BERT_TOKENIZER = transformers.BertTokenizer.from_pretrained("HooshvareLab/bert-fa-base-uncased", do_lower_case=False)
BERT_TOKENIZER.do_basic_tokenize = False
BERT_TOKENIZER.tokenize_chinese_chars = False
BERT_MAX_SEQ_LEN = 512

In [236]:
text = 'سلام خوفیی'
BERT_TOKENIZER.tokenize(text)

['سلام', 'خوف', '##یی']

In [237]:

def _custom_bert_tokenize_sentence(text):
    # from hazm import WordTokenizer
    new_tokens = []
    tokens = BERT_TOKENIZER.tokenize(text)
    # print(tokens)
    j = 0
    for i, t in enumerate(tokens):
        if t == '[UNK]':
            new_tokens.append(text.split()[j])
        else:
            new_tokens.append(t)
        if t[0] != '#':
            j += 1
    tokens = new_tokens
    print(tokens)
    tokens = tokens[:BERT_MAX_SEQ_LEN-2] # 2 allowed for [CLS] and [SEP]



    # # here they remove sub words with ## from list of words
    idxs = np.array([idx for idx,token in enumerate(tokens) if not token.startswith("##")]+[len(tokens)])
    print('-'*10)
    print(idxs[1:])
    print('-'*10)
    print(idxs[0:-1])
    print('-'*10)
    split_sizes = (idxs[1:]-idxs[0:-1]).tolist()
    # NOTE: BERT tokenizer does more than just splitting at whitespace and tokenizing. So be careful.
    # -----> assert len(split_sizes)==len(text.split()), print(len(tokens), len(split_sizes), len(text.split()), split_sizes, text)
    # -----> hence do the following:
    text = merge_subtokens(tokens)
    # print(text)
    assert len(split_sizes)==len(text.split()), print(len(tokens), len(split_sizes), len(text.split()), split_sizes, text)
    # print(text, tokens, split_sizes)
    return text, tokens, split_sizes


def _custom_bert_tokenize_sentences(list_of_texts):
    out = [_custom_bert_tokenize_sentence(text) for text in list_of_texts]
    texts, tokens, split_sizes = list(zip(*out))
    return [*texts], [*tokens], [*split_sizes]

_simple_bert_tokenize_sentences = \
    lambda list_of_texts: [merge_subtokens( BERT_TOKENIZER.tokenize(text)[:BERT_MAX_SEQ_LEN-2] ) for text in list_of_texts]


In [238]:

def bert_tokenize_for_valid_examples(batch_orginal_sentences, batch_noisy_sentences):
    """
    inputs:
        batch_noisy_sentences: List[str]
            a list of textual sentences to tokenized
        batch_orginal_sentences: List[str]
            a list of texts to make sure lengths of input and output are same in the seq-modeling task
    outputs (only of batch_noisy_sentences):
        batch_attention_masks, batch_input_ids, batch_token_type_ids
            2d tensors of shape (bs,max_len)
        batch_splits: List[List[Int]]
            specifies #sub-tokens for each word in each textual string after sub-word tokenization
    """
    _batch_orginal_sentences = _simple_bert_tokenize_sentences(batch_orginal_sentences)
    _batch_noisy_sentences, _batch_tokens, _batch_splits = _custom_bert_tokenize_sentences(batch_noisy_sentences)
    valid_idxs = [idx for idx,(a,b) in enumerate(zip(_batch_orginal_sentences, _batch_noisy_sentences)) if len(a.split())==len(b.split())]
    # print(valid_idxs)
    batch_orginal_sentences = [line for idx,line in enumerate(_batch_orginal_sentences) if idx in valid_idxs]
    batch_noisy_sentences = [line for idx,line in enumerate(_batch_noisy_sentences) if idx in valid_idxs]
    batch_tokens = [line for idx,line in enumerate(_batch_tokens) if idx in valid_idxs]
    batch_splits = [line for idx,line in enumerate(_batch_splits) if idx in valid_idxs]

    batch_bert_dict = {"attention_mask":[],"input_ids":[],"token_type_ids":[]}
    if len(valid_idxs)>0:
        batch_encoded_dicts = [BERT_TOKENIZER.encode_plus(tokens) for tokens in batch_tokens]
        batch_attention_masks = pad_sequence([torch.tensor(encoded_dict["attention_mask"]) for encoded_dict in batch_encoded_dicts],batch_first=True,padding_value=0)
        batch_input_ids = pad_sequence([torch.tensor(encoded_dict["input_ids"]) for encoded_dict in batch_encoded_dicts],batch_first=True,padding_value=0)
        batch_token_type_ids = pad_sequence([torch.tensor(encoded_dict["token_type_ids"]) for encoded_dict in batch_encoded_dicts],batch_first=True,padding_value=0)
        batch_bert_dict = {"attention_mask":batch_attention_masks,
                           "input_ids":batch_input_ids,
                           "token_type_ids":batch_token_type_ids}
    # print('-'*60)
    # print(batch_orginal_sentences)
    # print(batch_noisy_sentences)
    # print(batch_bert_dict)
    # print(batch_splits)
    # print('-'*60)

    return batch_orginal_sentences, batch_noisy_sentences, batch_bert_dict, batch_splits

In [239]:
def labelize(batch_labels, vocab):
    # print(batch_labels)

    #  so they have vocab
    token2idx, pad_token, unk_token = vocab["token2idx"], vocab["pad_token"], vocab["unk_token"]
    print('زنگی' in token2idx)

    list_list = [[token2idx[token] if token in token2idx else token2idx[unk_token] for token in line.split()] for line in batch_labels]
    list_tensors = [torch.tensor(x) for x in list_list]
    tensor_ = pad_sequence(list_tensors,batch_first=True,padding_value=token2idx[pad_token])
    # print('-'*30)
    # print(tensor_)
    # print(torch.tensor([len(x) for x in list_list]).long())
    # print('-'*30)

    return tensor_, torch.tensor([len(x) for x in list_list]).long()

In [240]:

def untokenize_without_unks(batch_predictions, batch_lengths, vocab, batch_clean_sentences, backoff="pass-through"):
    # print(10*'-')
    # , batch_lengths, vocab, batch_clean_sentences
    # print(batch_predictions)
    # print(10*'-')
    assert backoff in ["neutral","pass-through"], print(f"selected backoff strategy not implemented: {backoff}")
    idx2token = vocab["idx2token"]
    unktoken = vocab["token2idx"][vocab["unk_token"]]
    assert len(batch_predictions)==len(batch_lengths)==len(batch_clean_sentences)
    batch_clean_sentences = [sent.split() for sent in batch_clean_sentences]
    if backoff=="pass-through":
        batch_predictions = \
            [ " ".join( [   idx2token[idx] if idx!=unktoken else clean_[i] for i, idx in enumerate(pred_[:len_])  ] ) \
             for pred_,len_,clean_ in zip(batch_predictions,batch_lengths,batch_clean_sentences) ]
    elif backoff=="neutral":
        batch_predictions = \
            [ " ".join( [   idx2token[idx] if idx!=unktoken else "a" for i, idx in enumerate(pred_[:len_])  ] ) \
             for pred_,len_,clean_ in zip(batch_predictions,batch_lengths,batch_clean_sentences) ]
    return batch_predictions

def untokenize_without_unks2(batch_predictions, batch_lengths, vocab, batch_clean_sentences, topk=None):
    """
    batch_predictions are softmax probabilities and should have shape (batch_size,max_seq_len,vocab_size)
    batch_lengths should have shape (batch_size)
    batch_clean_sentences should be strings of shape (batch_size)
    """
    #print(batch_predictions.shape)
    idx2token = vocab["idx2token"]
    unktoken = vocab["token2idx"][vocab["unk_token"]]
    assert len(batch_predictions)==len(batch_lengths)==len(batch_clean_sentences)
    batch_clean_sentences = [sent.split() for sent in batch_clean_sentences]

    if topk is not None:
        # get topk items from dim=2 i.e top 5 prob inds
        batch_predictions = np.argpartition(-batch_predictions,topk,axis=-1)[:,:,:topk] # (batch_size,max_seq_len,5)
    #else:
    #    batch_predictions = batch_predictions # already have the topk indices

    # get topk words
    idx_to_token = lambda idx,idx2token,corresponding_clean_token,unktoken: idx2token[idx] if idx!=unktoken else corresponding_clean_token
    batch_predictions = \
    [[[idx_to_token(wordidx,idx2token,batch_clean_sentences[i][j],unktoken) \
       for wordidx in topk_wordidxs] \
      for j,topk_wordidxs in enumerate(predictions[:batch_lengths[i]])]  \
     for i,predictions in enumerate(batch_predictions)]

    return batch_predictions


In [241]:

def model_inference(model, data, topk, DEVICE, BATCH_SIZE=16, vocab_=None):
    """
        model: an instance of SubwordBert
        data: list of tuples, with each tuple consisting of correct and incorrect
                sentence string (would be split at whitespaces)
        topk: how many of the topk softmax predictions are considered for metrics calculations
        """
    if vocab_ is not None:
        vocab = vocab_
    print("###############################################")
    inference_st_time = time.time()
    _corr2corr, _corr2incorr, _incorr2corr, _incorr2incorr = 0, 0, 0, 0
    _mistakes = []
    VALID_BATCH_SIZE = BATCH_SIZE
    valid_loss = 0.
    print("data size: {}".format(len(data)))
    data_iter = batch_iter(data, batch_size=VALID_BATCH_SIZE, shuffle=False)
    model.eval()
    model.to(DEVICE)
    results = []
    line_index = 0
    for batch_id, (batch_labels, batch_sentences) in tqdm(enumerate(data_iter)):
        torch.cuda.empty_cache()
        st_time = time.time()
        # set batch data for bert
        batch_labels_, batch_sentences_, batch_bert_inp, batch_bert_splits = bert_tokenize_for_valid_examples(
            batch_labels, batch_sentences)
        # print(10*'-')
        # print(batch_labels_)
        # print(batch_sentences_)
        # print(batch_bert_inp)
        # print(batch_bert_splits)
        # print(10*'-')
        if len(batch_labels_) == 0:
            print("################")
            print("Not predicting the following lines due to pre-processing mismatch: \n")
            print([(a, b) for a, b in zip(batch_labels, batch_sentences)])
            print("################")
            continue
        else:
            batch_labels, batch_sentences = batch_labels_, batch_sentences_
        batch_bert_inp = {k: v.to(DEVICE) for k, v in batch_bert_inp.items()}
        # set batch data for others
        # # find words that not words
        batch_labels_ids, batch_lengths = labelize(batch_labels, vocab)
        batch_lengths = batch_lengths.to(DEVICE)
        batch_labels_ids = batch_labels_ids.to(DEVICE)

        try:
            with torch.no_grad():
                """
                NEW: batch_predictions can now be of shape (batch_size,batch_max_seq_len,topk) if topk>1, else (batch_size,batch_max_seq_len)
                """
                print('-'*10)

                print(batch_bert_inp)
                print('-'*10)

                print(batch_bert_splits)
                print('-'*10)

                print(batch_labels_ids)
                print('-'*10)

                print(topk)
                print('-'*10)
                batch_loss, batch_predictions = model(batch_bert_inp, batch_bert_splits, targets=batch_labels_ids,
                                                      topk=topk)
                print('-'*10)

                print(batch_loss)
                print(batch_predictions)
                print('-'*10)

        except RuntimeError:
            print(f"batch_bert_inp:{len(batch_bert_inp.keys())},batch_labels_ids:{batch_labels_ids.shape}")
            raise Exception("")
        valid_loss += batch_loss
        batch_lengths = batch_lengths.cpu().detach().numpy()
        if topk == 1:
            batch_predictions = untokenize_without_unks(batch_predictions, batch_lengths, vocab, batch_sentences)
        else:
            batch_predictions = untokenize_without_unks2(batch_predictions, batch_lengths, vocab, batch_sentences,
                                                         topk=None)
        batch_clean_sentences = [line for line in batch_labels]
        batch_corrupt_sentences = [line for line in batch_sentences]
        batch_predictions = [line for line in batch_predictions]

        for i, (a, b, c) in enumerate(zip(batch_clean_sentences, batch_corrupt_sentences, batch_predictions)):
            results.append({"id": line_index + i, "original": a, "noised": b, "predicted": c, "topk": [],
                            "topk_prediction_probs": [], "topk_reranker_losses": []})
        line_index += len(batch_clean_sentences)

        '''
        # update progress
        progressBar(batch_id+1,
                    int(np.ceil(len(data) / VALID_BATCH_SIZE)),
                    ["batch_time","batch_loss","avg_batch_loss","batch_acc","avg_batch_acc"],
                    [time.time()-st_time,batch_loss,valid_loss/(batch_id+1),None,None])
        '''
    print(f"\nEpoch {None} valid_loss: {valid_loss / (batch_id + 1)}")
    print("total inference time for this data is: {:4f} secs".format(time.time() - inference_st_time))
    print("###############################################")
    print("###############################################")
    return results

In [242]:

def spell_checking_on_sents(model, vocab, device, normalizer, txt):
    sents, splitters = get_sentences_splitters(txt)
    sents = [space_special_chars(s) for s in sents]
    sents = list(filter(lambda txt: (txt != '' and txt != ' '), sents))
    test_data = [(normalizer.normalize(t), normalizer.normalize(t)) for t in sents]
    print('inputs:')
    for t in test_data:
        print(t)
    greedy_results = model_inference(model, test_data, topk=1, DEVICE=device, BATCH_SIZE=1,
                                     vocab_=vocab)
    out = []
    for i, line in enumerate(greedy_results):
        ls = [(n, p) if n == p else ("**" + n + "**", "**" + p + "**") for n, p in
              zip(line["noised"].split(), line["predicted"].split())]
        y, z = map(list, zip(*ls))
        try:
            z = ' '.join(z)
            z = re.sub(r'\*\*(\w+)\*\*', r'** \1 **', z)
            z = re.sub(r'\*\* (\w+) \*\*', r'**\1**', z)
        except:
            z = ' '.join(z)
        out.append((" ".join(y), z))
    new_out = []
    for i, sent in enumerate(out):
            new_out.append( (de_space_special_chars(out[i][0]), de_space_special_chars(out[i][1])))
    return new_out, splitters

In [243]:
import os
import pickle

In [244]:
normalizer = Normalizer(punctuation_spacing=False, remove_extra_spaces=False)
vocab_path = os.path.join('model', 'vocab.pkl')
model_checkpoint_path = os.path.join('model', 'model.pth.tar')
model, vocab, device = load_pre_model(vocab_path=vocab_path, model_checkpoint_path=model_checkpoint_path)
#test
sample_input = 'این یکک مثالل صاده برالی ازرابی این سامانح اسصت'
output = spell_checking_on_sents(model, vocab, device, normalizer, sample_input)
print(output)

loading vocab from model/vocab.pkl
SubwordBert(
  (bert_dropout): Dropout(p=0.2, inplace=False)
  (bert_model): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(100000, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_feat

0it [00:00, ?it/s]

['این', 'یک', '##ک', 'مثال', '##ل', 'صاد', '##ه', 'برا', '##لی', 'ازرا', '##بی', 'این', 'سامان', '##ح', 'اس', '##صت']
----------
[ 1  3  5  7  9 11 12 14 16]
----------
[ 0  1  3  5  7  9 11 12 14]
----------
True
----------
{'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'input_ids': tensor([[    2,  2802,  2829,  2004,  4183,  2010,  4050,  2008,  9858,  2812,
         46254,  2877,  2802,  9819,  2051,  2876, 83441,     4]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])}
----------
[[1, 2, 2, 2, 2, 2, 1, 2, 2]]
----------
tensor([[     6, 100001, 100001, 100001, 100001, 100001,      6, 100001, 100001]])
----------
1
----------
torch.Size([1, 18, 768])
torch.Size([1, 9, 768])


1it [00:00,  3.20it/s]

----------
6.1808004
[[   6   13 1100 1611   12 1363    6 1154    9]]
----------

Epoch None valid_loss: 6.180800437927246
total inference time for this data is: 0.335225 secs
###############################################
###############################################
([('این **یکک** **مثالل** **صاده** **برالی** **ازرابی** این **سامانح** **اسصت**', 'این **یک** **مثال** **ساده** **برای** **ارزیابی** این **سامانه** **است**')], [])


In [245]:
# sample_input = 'این یکک مثالل صاده برالی ازرابی این ساماننح اسصت'
# sample_input = 'این دیگه چه جور زنگی ای است'
sample_input = 'مار زندگی'
output = spell_checking_on_sents(model, vocab, device, normalizer, sample_input)
print(output)

inputs:
('مار زندگی', 'مار زندگی')
###############################################
data size: 1


0it [00:00, ?it/s]

['مار', 'زندگی']
----------
[1 2]
----------
[0 1]
----------
True
----------
{'attention_mask': tensor([[1, 1, 1, 1]]), 'input_ids': tensor([[   2, 3955, 3351,    4]]), 'token_type_ids': tensor([[0, 0, 0, 0]])}
----------
[[1, 1]]
----------
tensor([[6310,  184]])
----------
1
----------


1it [00:00,  6.62it/s]

torch.Size([1, 4, 768])
torch.Size([1, 2, 768])
----------
1.9768447
[[ 46 184]]
----------

Epoch None valid_loss: 1.9768446683883667
total inference time for this data is: 0.164689 secs
###############################################
###############################################
([('**مار** زندگی', '**کار** زندگی')], [])


In [246]:
sample_input = 'این یکک مثالل صاده برالی ازرابی این ساماننح اسصت'
# sample_input = 'این دیگه چه جور گاری است'
output = spell_checking_on_sents(model, vocab, device, normalizer, sample_input)
print(output)

inputs:
('این یکک مثالل صاده برالی ازرابی این ساماننح اسصت', 'این یکک مثالل صاده برالی ازرابی این ساماننح اسصت')
###############################################
data size: 1


0it [00:00, ?it/s]

['این', 'یک', '##ک', 'مثال', '##ل', 'صاد', '##ه', 'برا', '##لی', 'ازرا', '##بی', 'این', 'سامان', '##ن', '##ح', 'اس', '##صت']
----------
[ 1  3  5  7  9 11 12 15 17]
----------
[ 0  1  3  5  7  9 11 12 15]
----------
True
----------
{'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'input_ids': tensor([[    2,  2802,  2829,  2004,  4183,  2010,  4050,  2008,  9858,  2812,
         46254,  2877,  2802,  9819,  2011,  2051,  2876, 83441,     4]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])}
----------
[[1, 2, 2, 2, 2, 2, 1, 3, 2]]
----------
tensor([[     6, 100001, 100001, 100001, 100001, 100001,      6, 100001, 100001]])
----------
1
----------
torch.Size([1, 19, 768])
torch.Size([1, 9, 768])


1it [00:00,  4.14it/s]

----------
5.705291
[[   6   13 1100 1611   12 1363    6 1154    9]]
----------

Epoch None valid_loss: 5.705290794372559
total inference time for this data is: 0.262556 secs
###############################################
###############################################
([('این **یکک** **مثالل** **صاده** **برالی** **ازرابی** این **ساماننح** **اسصت**', 'این **یک** **مثال** **ساده** **برای** **ارزیابی** این **سامانه** **است**')], [])
